// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// 🟢 2. บันทึกคะแนนดิบของผู้สมัครในหน่วยนั้น (Step 8)
	// Go จะรันคำสั่งนี้วนลูปตามจำนวนผู้สมัครที่ส่งคะแนนมา
	CreateStationCandidateVote(ctx context.Context, arg CreateStationCandidateVoteParams) error
	// ==========================================
	// BKK Election - SQL Queries (For sqlc)
	// ==========================================
	// 🟢 1. บันทึกข้อมูลสรุปของหน่วยเลือกตั้ง (Step 7)
	// ใช้ RETURNING id เพื่อเอา id ไปผูกกับตารางคะแนนย่อย
	CreateStationSubmission(ctx context.Context, arg CreateStationSubmissionParams) (int64, error)
	// ดึงข้อมูลสถิติของทุกเขต เพื่อเอาไปทำ Progress Bar
	GetAllDistrictStats(ctx context.Context) ([]DistrictStat, error)
	// ==========================================
	// 🔵 Queries สำหรับดึงข้อมูล (API / Read Model)
	// ==========================================
	// ดึง Leaderboard 5 อันดับแรกของ กทม. (ใช้ SUM รวมทุกเขต)
	GetOverallLeaderboard(ctx context.Context) ([]GetOverallLeaderboardRow, error)
	// 🟢 3. อัปเดตคะแนนรวมของเขตแบบ Atomic (Step 9)
	// ท่าไม้ตาย Upsert: ถ้าไม่มีข้อมูลเขตนี้/เบอร์นี้ ให้ INSERT ใหม่
	// แต่ถ้ามีแล้ว (ON CONFLICT) ให้เอาคะแนนเดิม + คะแนนใหม่ ($3)
	UpsertDistrictCandidateSummary(ctx context.Context, arg UpsertDistrictCandidateSummaryParams) error
	// 🟢 4. อัปเดตสถิติรวมของเขตแบบ Atomic (Step 10)
	// บวกยอดรวมบัตร และบวกจำนวนหน่วยที่ส่งแล้ว (submitted_stations + 1)
	UpsertDistrictStats(ctx context.Context, arg UpsertDistrictStatsParams) error
}

var _ Querier = (*Queries)(nil)
