// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Candidate struct {
	ID        int32              `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	PartyID   pgtype.Int4        `json:"party_id"`
	ImageUrl  pgtype.Text        `json:"image_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type District struct {
	ID     int32  `json:"id"`
	NameTh string `json:"name_th"`
	NameEn string `json:"name_en"`
}

type DistrictStat struct {
	DistrictID          int32              `json:"district_id"`
	TotalStations       int32              `json:"total_stations"`
	SubmittedStations   int32              `json:"submitted_stations"`
	TotalVotersCount    int32              `json:"total_voters_count"`
	TotalValidBallots   int32              `json:"total_valid_ballots"`
	TotalInvalidBallots int32              `json:"total_invalid_ballots"`
	TotalNoVotes        int32              `json:"total_no_votes"`
	LastUpdated         pgtype.Timestamptz `json:"last_updated"`
}

type DistrictSummary struct {
	ID          int64              `json:"id"`
	DistrictID  int32              `json:"district_id"`
	CandidateID int32              `json:"candidate_id"`
	TotalVotes  int64              `json:"total_votes"`
	LastUpdated pgtype.Timestamptz `json:"last_updated"`
}

type Party struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	ColorHex  string             `json:"color_hex"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PollingStation struct {
	ID             int32       `json:"id"`
	DistrictID     int32       `json:"district_id"`
	StationNumber  int32       `json:"station_number"`
	LocationName   pgtype.Text `json:"location_name"`
	EligibleVoters pgtype.Int4 `json:"eligible_voters"`
}

type StationCandidateVote struct {
	ID           int64       `json:"id"`
	SubmissionID pgtype.Int8 `json:"submission_id"`
	CandidateID  int32       `json:"candidate_id"`
	Votes        int32       `json:"votes"`
}

type StationSubmission struct {
	ID               int64              `json:"id"`
	IdempotencyKey   string             `json:"idempotency_key"`
	PollingStationID int32              `json:"polling_station_id"`
	DistrictID       int32              `json:"district_id"`
	VotersCount      int32              `json:"voters_count"`
	ValidBallots     int32              `json:"valid_ballots"`
	InvalidBallots   int32              `json:"invalid_ballots"`
	NoVotes          int32              `json:"no_votes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}
