// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStationCandidateVote = `-- name: CreateStationCandidateVote :exec
INSERT INTO station_candidate_votes (
    submission_id, candidate_id, votes
) VALUES (
    $1, $2, $3
)
`

type CreateStationCandidateVoteParams struct {
	SubmissionID pgtype.Int8 `json:"submission_id"`
	CandidateID  int32       `json:"candidate_id"`
	Votes        int32       `json:"votes"`
}

// 🟢 2. บันทึกคะแนนดิบของผู้สมัครในหน่วยนั้น (Step 8)
// Go จะรันคำสั่งนี้วนลูปตามจำนวนผู้สมัครที่ส่งคะแนนมา
func (q *Queries) CreateStationCandidateVote(ctx context.Context, arg CreateStationCandidateVoteParams) error {
	_, err := q.db.Exec(ctx, createStationCandidateVote, arg.SubmissionID, arg.CandidateID, arg.Votes)
	return err
}

const createStationSubmission = `-- name: CreateStationSubmission :one

INSERT INTO station_submissions (
    idempotency_key, polling_station_id, district_id, voters_count, valid_ballots, invalid_ballots, no_votes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id
`

type CreateStationSubmissionParams struct {
	IdempotencyKey   string `json:"idempotency_key"`
	PollingStationID int32  `json:"polling_station_id"`
	DistrictID       int32  `json:"district_id"`
	VotersCount      int32  `json:"voters_count"`
	ValidBallots     int32  `json:"valid_ballots"`
	InvalidBallots   int32  `json:"invalid_ballots"`
	NoVotes          int32  `json:"no_votes"`
}

// ==========================================
// BKK Election - SQL Queries (For sqlc)
// ==========================================
// 🟢 1. บันทึกข้อมูลสรุปของหน่วยเลือกตั้ง (Step 7)
// ใช้ RETURNING id เพื่อเอา id ไปผูกกับตารางคะแนนย่อย
func (q *Queries) CreateStationSubmission(ctx context.Context, arg CreateStationSubmissionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createStationSubmission,
		arg.IdempotencyKey,
		arg.PollingStationID,
		arg.DistrictID,
		arg.VotersCount,
		arg.ValidBallots,
		arg.InvalidBallots,
		arg.NoVotes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getAllDistrictStats = `-- name: GetAllDistrictStats :many
SELECT district_id, total_stations, submitted_stations, total_voters_count, total_valid_ballots, total_invalid_ballots, total_no_votes, last_updated FROM district_stats ORDER BY district_id
`

// ดึงข้อมูลสถิติของทุกเขต เพื่อเอาไปทำ Progress Bar
func (q *Queries) GetAllDistrictStats(ctx context.Context) ([]DistrictStat, error) {
	rows, err := q.db.Query(ctx, getAllDistrictStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DistrictStat
	for rows.Next() {
		var i DistrictStat
		if err := rows.Scan(
			&i.DistrictID,
			&i.TotalStations,
			&i.SubmittedStations,
			&i.TotalVotersCount,
			&i.TotalValidBallots,
			&i.TotalInvalidBallots,
			&i.TotalNoVotes,
			&i.LastUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverallLeaderboard = `-- name: GetOverallLeaderboard :many

SELECT candidate_id, SUM(total_votes)::bigint AS total_votes
FROM district_summaries
GROUP BY candidate_id
ORDER BY total_votes DESC
LIMIT 5
`

type GetOverallLeaderboardRow struct {
	CandidateID int32 `json:"candidate_id"`
	TotalVotes  int64 `json:"total_votes"`
}

// ==========================================
// 🔵 Queries สำหรับดึงข้อมูล (API / Read Model)
// ==========================================
// ดึง Leaderboard 5 อันดับแรกของ กทม. (ใช้ SUM รวมทุกเขต)
func (q *Queries) GetOverallLeaderboard(ctx context.Context) ([]GetOverallLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getOverallLeaderboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOverallLeaderboardRow
	for rows.Next() {
		var i GetOverallLeaderboardRow
		if err := rows.Scan(&i.CandidateID, &i.TotalVotes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDistrictCandidateSummary = `-- name: UpsertDistrictCandidateSummary :exec
INSERT INTO district_summaries (
    district_id, candidate_id, total_votes
) VALUES (
    $1, $2, $3
) ON CONFLICT (district_id, candidate_id)
DO UPDATE SET
    total_votes = district_summaries.total_votes + EXCLUDED.total_votes,
    last_updated = CURRENT_TIMESTAMP
`

type UpsertDistrictCandidateSummaryParams struct {
	DistrictID  int32 `json:"district_id"`
	CandidateID int32 `json:"candidate_id"`
	TotalVotes  int64 `json:"total_votes"`
}

// 🟢 3. อัปเดตคะแนนรวมของเขตแบบ Atomic (Step 9)
// ท่าไม้ตาย Upsert: ถ้าไม่มีข้อมูลเขตนี้/เบอร์นี้ ให้ INSERT ใหม่
// แต่ถ้ามีแล้ว (ON CONFLICT) ให้เอาคะแนนเดิม + คะแนนใหม่ ($3)
func (q *Queries) UpsertDistrictCandidateSummary(ctx context.Context, arg UpsertDistrictCandidateSummaryParams) error {
	_, err := q.db.Exec(ctx, upsertDistrictCandidateSummary, arg.DistrictID, arg.CandidateID, arg.TotalVotes)
	return err
}

const upsertDistrictStats = `-- name: UpsertDistrictStats :exec
INSERT INTO district_stats (
    district_id, submitted_stations, total_voters_count, total_valid_ballots, total_invalid_ballots, total_no_votes
) VALUES (
    $1, 1, $2, $3, $4, $5
) ON CONFLICT (district_id)
DO UPDATE SET
    submitted_stations = district_stats.submitted_stations + 1,
    total_voters_count = district_stats.total_voters_count + EXCLUDED.total_voters_count,
    total_valid_ballots = district_stats.total_valid_ballots + EXCLUDED.total_valid_ballots,
    total_invalid_ballots = district_stats.total_invalid_ballots + EXCLUDED.total_invalid_ballots,
    total_no_votes = district_stats.total_no_votes + EXCLUDED.total_no_votes,
    last_updated = CURRENT_TIMESTAMP
`

type UpsertDistrictStatsParams struct {
	DistrictID          int32 `json:"district_id"`
	TotalVotersCount    int32 `json:"total_voters_count"`
	TotalValidBallots   int32 `json:"total_valid_ballots"`
	TotalInvalidBallots int32 `json:"total_invalid_ballots"`
	TotalNoVotes        int32 `json:"total_no_votes"`
}

// 🟢 4. อัปเดตสถิติรวมของเขตแบบ Atomic (Step 10)
// บวกยอดรวมบัตร และบวกจำนวนหน่วยที่ส่งแล้ว (submitted_stations + 1)
func (q *Queries) UpsertDistrictStats(ctx context.Context, arg UpsertDistrictStatsParams) error {
	_, err := q.db.Exec(ctx, upsertDistrictStats,
		arg.DistrictID,
		arg.TotalVotersCount,
		arg.TotalValidBallots,
		arg.TotalInvalidBallots,
		arg.TotalNoVotes,
	)
	return err
}
